services:
  harmony-smp:
    image: rig14/harmony-smp-mysql:2.2.1
    container_name: smp
    profiles: [ "harmony-smp" ]
    volumes:
      - harmony-smp-data:/data
    ports:
      - "8080:8080"

  phoss-smp:
    image: phelger/phoss-smp-xml:latest
    container_name: smp
    profiles: [ "phoss-smp" ]
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=/config/application.properties
    volumes:
      - ./phoss-smp:/config:ro
      - smp-data:/home/git/conf
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  smp-data:
  harmony-smp-data:
